services:
  api:
    restart: always
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend/
    env_file:
      - .env
    networks:
      - server-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/frontend
    networks:
      - server-network

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "tunnel"
      - "--label"
      - "edge=edghts_2mQxKc42eRC8N9zE6M8IKRaHNdN"
      - "http://nginx:80"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    networks:
      - server-network

networks:
  server-network: {}