services:
  app:
    restart: always
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/
    env_file:
      - .env
    networks:
      - server-network

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "tunnel"
      - "--label"
      - "edge=edghts_2mQxKc42eRC8N9zE6M8IKRaHNdN"
      - "http://app:8501"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
    networks:
      - server-network

networks:
  server-network: {}